### ISSUE TITLE
Merge TRNdat and DISdat first

### ISSUE THREAD

**Issue by davidjpmoore** [davidjpmoore/HiPk2013#5]
TRNdat and DISdefshould be merged BEFORE merging with BGCdat and EFFdat

**Comment by davidjpmoore** [comment]
Recommend using dplyr join functions

**Comment by rlybrand4** [comment]
I just merged TRNdat with DISdef. I pushed the updated script back to github. Can you see the updates?

**Comment by davidjpmoore** [comment]
I've done some extensive hacking of the merging files - new issues arose
