### ISSUE TITLE
Merging 2+ data frames?

### ISSUE THREAD

**Issue by rlybrand4** [davidjpmoore/HiPk2013#6]
Any suggestions on the best method for merging 3 data frames? I was thinking DISdef, TRNdat, and BGCdat could be merged into one for easier plotting/analyses.

**Comment by davidjpmoore** [comment]
I would merge two... clean up the data frame ... then merge the third to that

Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------
From: rlybrand4
Date:04/28/2015 10:20 (GMT-07:00)
To: davidjpmoore/HiPk2013
Subject: [HiPk2013] Merging 2+ data frames? (#6)

Any suggestions on the best method for merging 3 data frames? I was thinking DISdef, TRNdat, and BGCdat could be merged into one for easier plotting/analyses.

##
