### ISSUE TITLE
Pushed new code

### ISSUE THREAD

**Issue by noelleje** [davidjpmoore/HiPk2013#7]
I tried to push a new script did it work? > "PlottingEEA_BGC.R"

**Comment by davidjpmoore** [comment]
Yes – this worked

From https://github.com/davidjpmoore/HiPk2013
   6a41863..5a911fa  master     -> origin/master
Updating 6a41863..5a911fa
Fast-forward
PlottingEEA_BGC.R | 70 +++++++++++++++++++++++++++++++++++++++++++++++++++++++
1 file changed, 70 insertions(+)
create mode 100644 PlottingEEA_BGC.R
