### ISSUE TITLE
Linear relationship?

### ISSUE THREAD

**Issue by davidjpmoore** [davidjpmoore/HiPk2013#8]
@noelleje 

Looking at the plots from your last update, I'm wondering if the relationship is really linear?  You might want to test whether the relationship is linear, quadratic or some other form.   If you fit different curves (assume linear, quadratic, ect) you can compare models using information theory. 
https://en.wikipedia.org/wiki/Akaike_information_criterion

**Comment by davidjpmoore** [comment]
@noelleje - I think you sent me an email about this a couple of weeks ago ... could you reply here and close or modify the issue here so we can keep track?

**Comment by noelleje** [comment]
AIC (phoslm, phosquadratic, phosglm, phosglm.log, phosgls, phosgls.log)

# df       AIC

# phoslm         3 1668.7666

# phosquadratic  4 1660.1921

# phosglm        3 1668.7666

# phosglm.log    3  399.5230

# phosgls        3 1660.5818

# phosgls.log    3  410.0036

# From these model comparisons it appears the glm with log tranformed data fits the best

This was from several models assuming normal distribution which is not the case for this data. Next steps are working on non-parametric analyses.
